In [1]:
import numpy as np
from kernelcpd import pelt, binseg
np.random.seed(123)

### EXAMPLE: CHANGE IN MEAN

In [2]:
# sample signal, 3 segments, 2 changepoints at index 29 and 59
seg_len = 30 # segment length
sd = 0.5
signal1 = np.column_stack((np.random.normal(1.0, sd, seg_len), np.random.normal(5.0, sd, seg_len)))
signal2 = np.column_stack((np.random.normal(5.0, sd, seg_len), np.random.normal(1.0, sd, seg_len)))
signal3 = np.column_stack((np.random.normal(4.0, sd, seg_len), np.random.normal(2.0, sd, seg_len)))
y = np.vstack((signal1, signal2, signal3))

In [3]:
pelt(sequence = y, pen = 2, model = 'L2')

array([15, 19])

In [4]:
pelt(sequence = y, pen = 0.1, model = 'srbf', T = 1, m=20)

array([29, 59])

In [5]:
binseg(sequence = y, model = 'srbf', n_changepoints=2, T = 4, m = 1)

array([29, 58])

### EXAMPLE: CHANGE IN VARIANCE

In [6]:
def generate_ar_change_data(n_samples=1000, bkp=500):
    res = np.zeros(n_samples)
    phi1 = [0.9]
    phi2 = [-0.9]
    noise = np.random.normal(0, 0.5, n_samples)
    for t in range(1, n_samples):
        if t < bkp:
            res[t] = phi1[0] * res[t-1] + noise[t]
        else:
            res[t] = phi2[0] * res[t-1] + noise[t]
    return res

In [7]:
for i in range(50):
    print(f"\n---- trial {i + 1} ----")
    y = generate_ar_change_data(200, 99).reshape(-1, 1)
    print(f"L2                   : {binseg(sequence = y, model = 'L2')}")
    print(f"srbf (T = 2, m = 2)  : {binseg(sequence = y, model = 'srbf', T = 2, m = 2)}")
    print(f"srbf (T = 2, m = 20) : {binseg(sequence = y, model = 'srbf', T = 2, m = 20)}")
    print(f"srbf (T = 10, m = 20): {binseg(sequence = y, model = 'srbf', T = 10, m = 20)}")
    print(f"srbf (T = 20, m = 20): {binseg(sequence = y, model = 'srbf', T = 20, m = 20)}")


---- trial 1 ----
L2                   : [75]
srbf (T = 2, m = 2)  : [177]
srbf (T = 2, m = 20) : [177]
srbf (T = 10, m = 20): [180]
srbf (T = 20, m = 20): [179]

---- trial 2 ----
L2                   : [53]
srbf (T = 2, m = 2)  : [166]
srbf (T = 2, m = 20) : [166]
srbf (T = 10, m = 20): [168]
srbf (T = 20, m = 20): [168]

---- trial 3 ----
L2                   : [44]
srbf (T = 2, m = 2)  : [154]
srbf (T = 2, m = 20) : [155]
srbf (T = 10, m = 20): [156]
srbf (T = 20, m = 20): [157]

---- trial 4 ----
L2                   : [28]
srbf (T = 2, m = 2)  : [197]
srbf (T = 2, m = 20) : [160]
srbf (T = 10, m = 20): [162]
srbf (T = 20, m = 20): [161]

---- trial 5 ----
L2                   : [35]
srbf (T = 2, m = 2)  : [165]
srbf (T = 2, m = 20) : [162]
srbf (T = 10, m = 20): [164]
srbf (T = 20, m = 20): [164]

---- trial 6 ----
L2                   : [11]
srbf (T = 2, m = 2)  : [197]
srbf (T = 2, m = 20) : [197]
srbf (T = 10, m = 20): [189]
srbf (T = 20, m = 20): [138]

---- trial 7 ----
L2 